# Use PostgreSQL for project database

default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: url_shortener_development

test:
  <<: *default
  database: url_shortener_test

production:
  <<: *default
  database: url_shortener_production
  username: <%= ENV['URL_SHORTENER_DB_PRODUCTION_USER'] %>
  password: <%= ENV['URL_SHORTENER_DB_PRODUCTION_PASSWORD'] %>